
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-a
  template:
    metadata:
      labels:
        app: feature-a
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=Hello from feature‑A"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: feature-a
spec:
  selector:
    app: feature-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: ClusterIP
# ci test Thu Jul 17 12:03:06 PDT 2025
