apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-b
  template:
    metadata:
      labels:
        app: feature-b
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=Greetings from feature‑B"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: feature-b
spec:
  selector:
    app: feature-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: 
